name: Deploy Flutter Web to CapRover

on:
  push:
    branches: [ "master" ]  # ili glavni branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Install CapRover CLI
        run: npm install -g caprover@latest

      - name: Archive Flutter Web + Captain Definition
        run: |
          tar -czf build_web_with_captain.tar.gz captain-definition build/web

      - name: List tar content (debug)
        run: tar -tzf build_web_with_captain.tar.gz

      - name: Deploy to CapRover
        env:
          CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
          CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
          CAPROVER_APP: ${{ secrets.CAPROVER_APP }}
        run: |
          caprover deploy --tarFile build_web_with_captain.tar.gz --appName $CAPROVER_APP





